jobs:
- job: A1
  steps:
  - bash: echo "A1"

- job: A2
  steps:
  - bash: echo "A2"
- job: B1
  steps:
  - bash: echo "B1"

stages:
- stage: A
  jobs:
  - job: A1
  - job: A2

- stage: B
  jobs:
  - job: B1
  