# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'dockerjb8/docker-web-app'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    tags: test1
    command: build
    Dockerfile: docker-web-app/Dockerfile

- task: Docker@2
  displayName: Push the image
  inputs:
    containerRegistry: jbDockerHubConnection
    repository: $(imageName)
    command: push
    tags: |
      test1