# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'dockerjb/docker-web-app'

